version: "3.8"
services:
    app:
        build: ./docker/app/.
        container_name: taskory-app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - taskory-network

    web:
        image: nginx:alpine
        container_name: taskory-web
        working_dir: /var/www/html
        ports:
            - '8001:80'
        volumes:
            - .:/var/www/html
            - ./docker/web/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - taskory-network

    db:
        image: mysql:8.0.34
        container_name: taskory-db
        restart: always
        environment:
            - MYSQL_DATABASE=dev
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=app
            - MYSQL_PASSWORD=apppass
        volumes:
            - ./docker/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - mysql_data:/var/lib/mysql:cached
        ports:
            - '8982:3306'
        networks:
            - taskory-network

networks:
    taskory-network:
        driver: bridge

volumes:
    mysql_data:
